export const categoryList = [
  {
    id: 1,
    name: "Skaboo",
    slug: "Honorable",
    is_active: false,
    created_at: "11/25/2022",
  },
  {
    id: 2,
    name: "Quatz",
    slug: "Ms",
    is_active: true,
    created_at: "12/21/2022",
  },
  {
    id: 3,
    name: "Roombo",
    slug: "Honorable",
    is_active: false,
    created_at: "9/27/2022",
  },
  {
    id: 4,
    name: "Midel",
    slug: "Mr",
    is_active: true,
    created_at: "9/14/2022",
  },
  {
    id: 5,
    name: "Skaboo",
    slug: "Mr",
    is_active: true,
    created_at: "12/1/2022",
  },
  {
    id: 6,
    name: "Jaxspan",
    slug: "Ms",
    is_active: true,
    created_at: "6/5/2022",
  },
  {
    id: 7,
    name: "Buzzbean",
    slug: "Dr",
    is_active: true,
    created_at: "6/20/2022",
  },
  {
    id: 8,
    name: "Linkbuzz",
    slug: "Mrs",
    is_active: false,
    created_at: "9/9/2022",
  },
  {
    id: 9,
    name: "Browseblab",
    slug: "Rev",
    is_active: false,
    created_at: "1/18/2023",
  },
  {
    id: 10,
    name: "Yabox",
    slug: "Honorable",
    is_active: true,
    created_at: "11/23/2022",
  },
  {
    id: 11,
    name: "Skidoo",
    slug: "Ms",
    is_active: true,
    created_at: "8/6/2022",
  },
  {
    id: 12,
    name: "Feednation",
    slug: "Ms",
    is_active: true,
    created_at: "8/12/2022",
  },
  {
    id: 13,
    name: "Abatz",
    slug: "Dr",
    is_active: true,
    created_at: "8/16/2022",
  },
  {
    id: 14,
    name: "Skilith",
    slug: "Dr",
    is_active: true,
    created_at: "5/22/2022",
  },
  {
    id: 15,
    name: "Dabfeed",
    slug: "Mrs",
    is_active: true,
    created_at: "1/22/2022",
  },
  {
    id: 16,
    name: "Izio",
    slug: "Mrs",
    is_active: true,
    created_at: "4/4/2022",
  },
  {
    id: 17,
    name: "Brightbean",
    slug: "Mrs",
    is_active: false,
    created_at: "5/8/2022",
  },
  {
    id: 18,
    name: "Brainsphere",
    slug: "Dr",
    is_active: true,
    created_at: "5/22/2022",
  },
  {
    id: 19,
    name: "Yakitri",
    slug: "Rev",
    is_active: true,
    created_at: "10/26/2022",
  },
  {
    id: 20,
    name: "Quinu",
    slug: "Ms",
    is_active: true,
    created_at: "12/20/2022",
  },
  {
    id: 21,
    name: "Zoozzy",
    slug: "Mrs",
    is_active: false,
    created_at: "5/13/2022",
  },
  {
    id: 22,
    name: "Rooxo",
    slug: "Honorable",
    is_active: true,
    created_at: "7/1/2022",
  },
  {
    id: 23,
    name: "Lajo",
    slug: "Honorable",
    is_active: true,
    created_at: "8/3/2022",
  },
  {
    id: 24,
    name: "Dynava",
    slug: "Mr",
    is_active: false,
    created_at: "10/5/2022",
  },
  {
    id: 25,
    name: "Thoughtblab",
    slug: "Rev",
    is_active: true,
    created_at: "7/18/2022",
  },
  {
    id: 26,
    name: "Shuffledrive",
    slug: "Mr",
    is_active: true,
    created_at: "1/15/2023",
  },
  {
    id: 27,
    name: "Yakijo",
    slug: "Dr",
    is_active: false,
    created_at: "1/9/2023",
  },
  {
    id: 28,
    name: "Demivee",
    slug: "Rev",
    is_active: false,
    created_at: "7/20/2022",
  },
  {
    id: 29,
    name: "Roombo",
    slug: "Mrs",
    is_active: false,
    created_at: "9/21/2022",
  },
  {
    id: 30,
    name: "Twinte",
    slug: "Rev",
    is_active: true,
    created_at: "8/8/2022",
  },
  {
    id: 31,
    name: "Wordify",
    slug: "Honorable",
    is_active: true,
    created_at: "3/22/2022",
  },
  {
    id: 32,
    name: "JumpXS",
    slug: "Mrs",
    is_active: false,
    created_at: "4/14/2022",
  },
  {
    id: 33,
    name: "Aimbo",
    slug: "Mrs",
    is_active: false,
    created_at: "4/3/2022",
  },
  {
    id: 34,
    name: "Fivespan",
    slug: "Rev",
    is_active: true,
    created_at: "1/9/2023",
  },
  {
    id: 35,
    name: "Yozio",
    slug: "Rev",
    is_active: true,
    created_at: "12/9/2022",
  },
  {
    id: 36,
    name: "Twinte",
    slug: "Mrs",
    is_active: false,
    created_at: "3/25/2022",
  },
  {
    id: 37,
    name: "Skipfire",
    slug: "Ms",
    is_active: false,
    created_at: "6/17/2022",
  },
  {
    id: 38,
    name: "Reallinks",
    slug: "Dr",
    is_active: true,
    created_at: "6/22/2022",
  },
  {
    id: 39,
    name: "Innojam",
    slug: "Mrs",
    is_active: true,
    created_at: "10/20/2022",
  },
  {
    id: 40,
    name: "Feednation",
    slug: "Honorable",
    is_active: true,
    created_at: "2/21/2022",
  },
  {
    id: 41,
    name: "Yacero",
    slug: "Mrs",
    is_active: false,
    created_at: "5/10/2022",
  },
  {
    id: 42,
    name: "Dynava",
    slug: "Dr",
    is_active: false,
    created_at: "10/12/2022",
  },
  {
    id: 43,
    name: "Brainsphere",
    slug: "Ms",
    is_active: false,
    created_at: "5/15/2022",
  },
  {
    id: 44,
    name: "Eidel",
    slug: "Mrs",
    is_active: true,
    created_at: "7/26/2022",
  },
  {
    id: 45,
    name: "Linkbuzz",
    slug: "Dr",
    is_active: false,
    created_at: "3/13/2022",
  },
  {
    id: 46,
    name: "Youbridge",
    slug: "Rev",
    is_active: false,
    created_at: "1/11/2023",
  },
  {
    id: 47,
    name: "Tekfly",
    slug: "Ms",
    is_active: true,
    created_at: "1/11/2023",
  },
  {
    id: 48,
    name: "Miboo",
    slug: "Mrs",
    is_active: false,
    created_at: "9/11/2022",
  },
  {
    id: 49,
    name: "Meemm",
    slug: "Mrs",
    is_active: true,
    created_at: "1/27/2022",
  },
  {
    id: 50,
    name: "Kayveo",
    slug: "Rev",
    is_active: false,
    created_at: "9/17/2022",
  },
];
