export const dummyDataJobs = [
  {
    id: 1,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 2,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 3,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 4,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 5,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 6,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 7,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 8,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 9,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
  {
    id: 10,
    ownerName: "jules",
    phone: "514 248 9502",
    jobDescription: " some description of the job here",
    location: "10380 terasse fleury",
    town: "Montréal",
    province: "Québec",
    publishDate: "2022-09-28",
    jobDate: "2022-09-31",
    ownerPrice: 25,
    isEnterprise: "no",
    isParticular: "yes",
  },
];
